language: ruby
rvm:
  - 1.9.3
  - jruby-19mode
  - rbx-19mode
  - ruby-head
  - jruby-head
  - 2.0.0
matrix:
  allow_failures:
    - rvm: jruby-19mode
    - rvm: rbx-19mode
    - rvm: ruby-head
    - rvm: jruby-head
    - rvm: 2.0.0
notifications:
  email: false
